DROP TABLE IF EXISTS test;
CREATE TABLE test (
  id VARCHAR(63) PRIMARY KEY,
  code VARCHAR(63) NOT NULL COMMENT '编码',
  name VARCHAR(63) NOT NULL COMMENT '名称',
  created_time DATETIME  DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
  creator_id VARCHAR(63) NOT NULL COMMENT '创建者主键',
  modified_time DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '最近修改时间',
  modifier_id VARCHAR(63) NOT NULL COMMENT '最近修改者主键'
) ;